# Generated by Django 2.0.6 on 2018-09-21 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shufic', '0007_auto_20180917_2127'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table=None,
        ),
    ]
